settings:
  title: 'Xanzhu Status Page'
  url: '' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: a2
    name: Vercel - a2.xanzhu.com
    description: 'Latest developer preview from Vercel'
    url: 'https://a2.xanzhu.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: a3
    name: Cloudflare - a3.xanzhu.com
    description: 'Latest developer preview from Cloudflare'
    url: 'https://a3.xanzhu.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: a4
    name: Netlify - a4.xanzhu.com
    description: 'Latest developer preview from Netlify'
    url: 'https://a4.xanzhu.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Current - xanzhu.com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
