settings:
  title: 'Xanzhu Status Page'
  url: '' # used for Slack messages
  logo: logo.png #
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: a2
    name: a2.xanzhu.com (Vercel)
    description: 'Latest developer preview from Vercel'
    url: 'https://a2.xanzhu.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: a3
    name: xanzhu.pages.dev (Cloudflare)
    description: 'Latest developer preview from Cloudflare'
    url: 'https://xanzhu.pages.dev'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: a4
    name: a4.xanzhu.com (Netlify)
    description: 'Latest developer preview from Netlify'
    url: 'https://a4.xanzhu.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: xanzhu.com
    name: 'Latest Production release from Vercel'
    url: 'https://xanzhu.com/'
    method: GET
    expectStatus: 200
